# Generated by Django 3.0.7 on 2020-11-01 08:31

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='contact phone number', max_length=31),
        ),
    ]
